apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: names-app-volume-pvc 
spec:
  accessModes: 
    - ReadWriteMany
  storageClassName: names-app-storage
  resources:
    requests:
      storage: 2Gi
---

apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: names-app-storage
provisioner: ebs.csi.aws.com
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
parameters:
  csi.storage.k8s.io/fstype: xfs
  type: gp3